# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_converter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_converter.proto\x12\rfileconverter\"q\n\x0e\x43onvertRequest\x12)\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x16.fileconverter.CommandH\x00\x12)\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x18.fileconverter.FileChunkH\x00\x42\t\n\x07payload\"F\n\x07\x43ommand\x12\x0f\n\x07src_ext\x18\x01 \x01(\t\x12\x0f\n\x07\x64st_ext\x18\x02 \x01(\t\x12\x19\n\x11original_filename\x18\x03 \x01(\t\"\x19\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x9b\x01\n\x0f\x43onvertResponse\x12+\n\x04info\x18\x01 \x01(\x0b\x32\x1b.fileconverter.ResponseInfoH\x00\x12)\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x18.fileconverter.FileChunkH\x00\x12%\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x14.fileconverter.ErrorH\x00\x42\t\n\x07payload\"\'\n\x0cResponseInfo\x12\x17\n\x0foutput_filename\x18\x01 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t2]\n\rFileConverter\x12L\n\x07\x43onvert\x12\x1d.fileconverter.ConvertRequest\x1a\x1e.fileconverter.ConvertResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=39
  _globals['_CONVERTREQUEST']._serialized_end=152
  _globals['_COMMAND']._serialized_start=154
  _globals['_COMMAND']._serialized_end=224
  _globals['_FILECHUNK']._serialized_start=226
  _globals['_FILECHUNK']._serialized_end=251
  _globals['_CONVERTRESPONSE']._serialized_start=254
  _globals['_CONVERTRESPONSE']._serialized_end=409
  _globals['_RESPONSEINFO']._serialized_start=411
  _globals['_RESPONSEINFO']._serialized_end=450
  _globals['_ERROR']._serialized_start=452
  _globals['_ERROR']._serialized_end=476
  _globals['_FILECONVERTER']._serialized_start=478
  _globals['_FILECONVERTER']._serialized_end=571
# @@protoc_insertion_point(module_scope)
